// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type User struct {
	ID       int64          `json:"id"`
	Username string         `json:"username"`
	Email    sql.NullString `json:"email"`
}

type UserKey struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	Fingerprint string `json:"fingerprint"`
	PublicKey   string `json:"public_key"`
}
