// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type User struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

type UserKey struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	Fingerprint string `json:"fingerprint"`
	PublicKey   string `json:"public_key"`
}
