// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email) VALUES (?, ?) RETURNING id, username, email
`

type CreateUserParams struct {
	Username string         `json:"username"`
	Email    sql.NullString `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}

const linkKeyToUser = `-- name: LinkKeyToUser :exec
INSERT INTO user_keys (user_id, fingerprint, public_key)
VALUES (?, ?, ?)
ON CONFLICT (fingerprint, user_id) DO NOTHING
`

type LinkKeyToUserParams struct {
	UserID      int64  `json:"user_id"`
	Fingerprint string `json:"fingerprint"`
	PublicKey   string `json:"public_key"`
}

// Re-linking an already known pair is a no-op, so a returning player can sign
// in from the same key repeatedly.
func (q *Queries) LinkKeyToUser(ctx context.Context, arg LinkKeyToUserParams) error {
	_, err := q.db.ExecContext(ctx, linkKeyToUser, arg.UserID, arg.Fingerprint, arg.PublicKey)
	return err
}

const listUsersByEmail = `-- name: ListUsersByEmail :many
SELECT id, username, email FROM users WHERE email = ? ORDER BY id
`

// The cross-client counterpart of ListUsersByFingerprint: an address reaches
// every character the person holds. Callers pass a lowercased address.
func (q *Queries) ListUsersByEmail(ctx context.Context, email sql.NullString) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Username, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByFingerprint = `-- name: ListUsersByFingerprint :many
SELECT u.id, u.username, u.email
FROM users u
JOIN user_keys k ON k.user_id = u.id
WHERE k.fingerprint = ?
ORDER BY u.id
`

// Every account reachable from one SSH key, oldest first so the menu order is
// stable across logins.
func (q *Queries) ListUsersByFingerprint(ctx context.Context, fingerprint string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByFingerprint, fingerprint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Username, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
